version: "3.9"
services:
  burger-reviews-redis:
    image: redis:6.0.10
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
  burger-reviews:
    build: .
    ports:
      - "9090:9090"
    environment:
      - BURGER_REVIEWS_DEV_MODE=${BURGER_REVIEWS_DEV_MODE}
      - TOKEN_EXPIRE_TIME=${TOKEN_EXPIRE_TIME}
      - MAX_TOKENS_PER_IP=${MAX_TOKENS_PER_IP}
      - IS_HTTPS=${IS_HTTPS}
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - SERVER_PORT=${SERVER_PORT}
      - SERVE_ON_PATH=${SERVE_ON_PATH}
      - CONSTANTS_PATH=${CONSTANTS_PATH}
      - FRONTEND_DIR=${FRONTEND_DIR}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - "./constants.json:/app/backend/constants.json"
    links:
      - "burger-reviews-redis"
    depends_on:
      - "burger-reviews-redis"